####################
## Package Groups ##
####################

packages:
  - apps/*
  - libs/*
  - tools/*

catalog:
  "@types/node": ^24
  cspell: ^9.7.0
  react-day-picker: ^9.14.0
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

##############
## Catalogs ##
##############

catalogMode: prefer

overrides:
  vite: "catalog:"
  vitest: "catalog:"

######################
# Peer Dependencies ##
######################

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
